// ─────────────────────────────────────────────────────────────
//  build.js  —  Vercel build script
//
//  Reads environment variables set in the Vercel dashboard and
//  writes config.js so the static HTML can load them at runtime.
//
//  Vercel Environment Variables to set in your project dashboard:
//  ┌─────────────────────────────┬──────────────────────────────────────────┐
//  │ Variable Name               │ Value                                    │
//  ├─────────────────────────────┼──────────────────────────────────────────┤
//  │ FIREBASE_API_KEY            │ AIzaSyCzm8K9V3rHZi0jlXfHyQGHyiIFd2CYsbo │
//  │ FIREBASE_AUTH_DOMAIN        │ sptrack-64a70.firebaseapp.com            │
//  │ FIREBASE_PROJECT_ID         │ sptrack-64a70                            │
//  │ FIREBASE_STORAGE_BUCKET     │ sptrack-64a70.firebasestorage.app        │
//  │ FIREBASE_MESSAGING_SENDER   │ 670922869352                             │
//  │ FIREBASE_APP_ID             │ 1:670922869352:web:2fa6829d1e95ea3485c9dd│
//  │ EMAILJS_PUBLIC_KEY          │ 17S5CavnDP7UTfVFG                        │
//  │ EMAILJS_SERVICE_ID          │ service_j9pwgpo                          │
//  │ EMAILJS_OTP_TEMPLATE_ID     │ template_o1dri9d                         │
//  │ EMAILJS_RESET_TEMPLATE_ID   │ template_9o17ztf                         │
//  │ EMAILJS_PRIVATE_KEY         │ 6Vr6j3s0PusK2DE6GdI39  ← SERVER ONLY    │
//  └─────────────────────────────┴──────────────────────────────────────────┘
//
//  EMAILJS_PRIVATE_KEY is stored here for reference but is intentionally
//  NOT written into config.js — it stays server-side only.
// ─────────────────────────────────────────────────────────────

const fs = require('fs');
const path = require('path');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER',
  'FIREBASE_APP_ID',
  'EMAILJS_PUBLIC_KEY',
  'EMAILJS_SERVICE_ID',
  'EMAILJS_OTP_TEMPLATE_ID',
  'EMAILJS_RESET_TEMPLATE_ID'
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('[build] ❌ Missing environment variables:', missing.join(', '));
  process.exit(1);
}

const content = `// AUTO-GENERATED by build.js — DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
window.APP_CONFIG = {
  firebase: {
    apiKey:            "${process.env.FIREBASE_API_KEY}",
    authDomain:        "${process.env.FIREBASE_AUTH_DOMAIN}",
    projectId:         "${process.env.FIREBASE_PROJECT_ID}",
    storageBucket:     "${process.env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER}",
    appId:             "${process.env.FIREBASE_APP_ID}"
  },
  emailjs: {
    publicKey:       "${process.env.EMAILJS_PUBLIC_KEY}",
    serviceId:       "${process.env.EMAILJS_SERVICE_ID}",
    otpTemplateId:   "${process.env.EMAILJS_OTP_TEMPLATE_ID}",
    resetTemplateId: "${process.env.EMAILJS_RESET_TEMPLATE_ID}"
  }
};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), content, 'utf8');
console.log('[build] ✅ config.js generated successfully.');
