// ─────────────────────────────────────────────────────────────
//  SpendTrack — App Configuration
//
//  ⚠️  This file is listed in .gitignore.
//      It is NEVER committed to Git.
//
//  For LOCAL development  → edit the values below directly.
//  For VERCEL deployment  → values are auto-generated by
//                           build.js from Vercel Environment
//                           Variables (see vercel.json).
//
//  🔒 PRIVATE KEY note:
//      Your EmailJS Private Key is a server-side secret.
//      Do NOT add it here. Store it only in Vercel Environment
//      Variables (EMAILJS_PRIVATE_KEY) and use it exclusively
//      inside an /api/* serverless function — never in the browser.
// ─────────────────────────────────────────────────────────────

window.APP_CONFIG = {

  // ── Firebase ───────────────────────────────────────────────
  firebase: {
    apiKey:            "AIzaSyCzm8K9V3rHZi0jlXfHyQGHyiIFd2CYsbo",
    authDomain:        "sptrack-64a70.firebaseapp.com",
    projectId:         "sptrack-64a70",
    storageBucket:     "sptrack-64a70.firebasestorage.app",
    messagingSenderId: "670922869352",
    appId:             "1:670922869352:web:2fa6829d1e95ea3485c9dd"
  },

  // ── EmailJS (client-side keys only) ────────────────────────
  emailjs: {
    publicKey:       "17S5CavnDP7UTfVFG",
    serviceId:       "service_j9pwgpo",
    otpTemplateId:   "template_o1dri9d",
    resetTemplateId: "template_9o17ztf"
    // privateKey → Vercel env var EMAILJS_PRIVATE_KEY (server-side only)
  }

};
